In [314]:
import numpy as np

## Data Types and attributes

In [315]:
x = np.array([1, 2, 3])

In [316]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

In [317]:
z = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9.5]]])

### Attributes

In [318]:
x.shape, y.shape, z.shape

((3,), (2, 3), (1, 3, 3))

In [319]:
x.ndim, y.ndim, z.ndim

(1, 2, 3)

In [320]:
x.dtype, y.dtype, z.dtype

(dtype('int32'), dtype('int32'), dtype('float64'))

In [321]:
x.size, y.size, z.size

(3, 6, 9)

In [322]:
type(x), type(y), type(z)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

### Create a Dataframe from a numpy array

In [323]:
import pandas as pd

In [324]:
y2 = pd.DataFrame(y)

In [325]:
y2

0  1  2
0  1  2  3
1  4  5  6

In [326]:
type(y2)

pandas.core.frame.DataFrame

## Creating arrays

In [327]:
ones = np.ones((5, 3))

In [328]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [329]:
ones.dtype

dtype('float64')

In [330]:
type(ones)

numpy.ndarray

In [331]:
zeros = np.zeros((5,4))

In [332]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [333]:
range_arrays = np.arange(2, 12, 2)

In [334]:
range_arrays

array([ 2,  4,  6,  8, 10])

In [335]:
random_array = np.random.randint(1, 100, 10)

In [336]:
random_array

array([89, 82, 38, 26, 78, 73, 10, 21, 81, 70])

In [337]:
random_array2 = np.random.randint(0, 50, size = (3,8))

In [338]:
random_array2

array([[15, 47,  0, 18, 35, 24, 49, 29],
       [19, 19, 14, 39, 32,  1,  9, 32],
       [31, 10, 23, 35, 11, 28, 34,  0]])

In [339]:
random_array3 = np.random.randint(999, size = (2,2))

In [340]:
random_array3

array([[128, 932],
       [ 53, 901]])

In [341]:
random_array3.size, random_array3.shape

(4, (2, 2))

In [342]:
type(random_array3), random_array3.dtype

(numpy.ndarray, dtype('int32'))

## Pseudo-random numbers

In [343]:
#Pseudo-random numbers

In [344]:
a = np.random.randint(0, 20, size = (5, 4))

In [345]:
a

array([[ 6,  8, 17, 15],
       [ 4,  9, 10,  1],
       [ 1,  7,  9,  3],
       [ 6, 11, 14, 18],
       [ 0, 14,  3, 12]])

### Random Seed

In [346]:
np.random.seed(0)
b = np.random.randint(30, size = (6, 4))

In [347]:
b

array([[12, 15, 21,  0],
       [ 3, 27,  3,  7],
       [ 9, 19, 21, 18],
       [ 4, 23,  6, 24],
       [24, 12, 26,  1],
       [ 6,  7, 23, 14]])

In [348]:
np.unique(a)

array([ 0,  1,  3,  4,  6,  7,  8,  9, 10, 11, 12, 14, 15, 17, 18])

In [349]:
np.unique(b)

array([ 0,  1,  3,  4,  6,  7,  9, 12, 14, 15, 18, 19, 21, 23, 24, 26, 27])

## Viewing arrays and Matrices

In [350]:
#indexing
a[1]

array([ 4,  9, 10,  1])

In [351]:
b

array([[12, 15, 21,  0],
       [ 3, 27,  3,  7],
       [ 9, 19, 21, 18],
       [ 4, 23,  6, 24],
       [24, 12, 26,  1],
       [ 6,  7, 23, 14]])

In [352]:
b[0]

array([12, 15, 21,  0])

In [353]:
b.shape

(6, 4)

In [354]:
c = np.random.randint(15, size = (2,2,3,2))

In [355]:
c

array([[[[ 8,  1],
         [ 5,  9],
         [13,  8]],

        [[ 9,  4],
         [ 3,  0],
         [ 3,  5]]],


       [[[14,  0],
         [ 2,  3],
         [ 8,  1]],

        [[ 3, 13],
         [ 3,  3],
         [14,  7]]]])

In [356]:
c.shape, c.ndim

((2, 2, 3, 2), 4)

In [357]:
c[:,:,:,:1]

array([[[[ 8],
         [ 5],
         [13]],

        [[ 9],
         [ 3],
         [ 3]]],


       [[[14],
         [ 2],
         [ 8]],

        [[ 3],
         [ 3],
         [14]]]])

# Manipulating and comparing arrays

## Arithmetic

In [358]:
x

array([1, 2, 3])

In [359]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [360]:
ones = np.ones(3)

In [361]:
ones

array([1., 1., 1.])

In [362]:
ones.shape

(3,)

In [363]:
x * ones

array([1., 2., 3.])

In [364]:
x + ones

array([2., 3., 4.])

In [365]:
x - ones

array([0., 1., 2.])

In [366]:
np.random.seed(seed =0)
twos = np.random.randint(10, size = (3))

In [367]:
twos

array([5, 0, 3])

In [368]:
x * twos

array([5, 0, 9])

In [369]:
x + twos

array([6, 2, 6])

In [370]:
d = np.random.randint(10, size = (2, 3))

In [371]:
d

array([[3, 7, 9],
       [3, 5, 2]])

In [372]:
x * d

array([[ 3, 14, 27],
       [ 3, 10,  6]])

In [373]:
d // x

array([[3, 3, 3],
       [3, 2, 0]])

In [374]:
x // d

array([[0, 0, 0],
       [0, 0, 1]])

In [375]:
d % x

array([[0, 1, 0],
       [0, 1, 2]])

In [376]:
np.square(x)

array([1, 4, 9])

In [377]:
np.square(d)

array([[ 9, 49, 81],
       [ 9, 25,  4]])

In [378]:
np.log(d)

array([[1.09861229, 1.94591015, 2.19722458],
       [1.09861229, 1.60943791, 0.69314718]])

# Aggregation

In [379]:
e = np.random.random(1000000)

In [380]:
e[:10]

array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
       0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ])

In [381]:
%timeit np.sum(e) #numpy's sum

1.93 ms ± 146 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [382]:
%timeit sum(e) #Python's sum

157 ms ± 7.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Reshaping and Transposing

In [383]:
x

array([1, 2, 3])

In [384]:
y, y.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [385]:
z, z.shape

(array([[[1. , 2. , 3. ],
         [4. , 5. , 6. ],
         [7. , 8. , 9.5]]]),
 (1, 3, 3))

In [386]:
z2 = z.reshape(9,1,1)

In [387]:
z2 * y

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 2. ,  4. ,  6. ],
        [ 8. , 10. , 12. ]],

       [[ 3. ,  6. ,  9. ],
        [12. , 15. , 18. ]],

       [[ 4. ,  8. , 12. ],
        [16. , 20. , 24. ]],

       [[ 5. , 10. , 15. ],
        [20. , 25. , 30. ]],

       [[ 6. , 12. , 18. ],
        [24. , 30. , 36. ]],

       [[ 7. , 14. , 21. ],
        [28. , 35. , 42. ]],

       [[ 8. , 16. , 24. ],
        [32. , 40. , 48. ]],

       [[ 9.5, 19. , 28.5],
        [38. , 47.5, 57. ]]])

In [388]:
z.T.shape

(3, 3, 1)

## .dot(product)

In [389]:
y2

0  1  2
0  1  2  3
1  4  5  6

In [390]:
# Transposing a matrix
y2 = y.T

In [391]:
z

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9.5]]])

In [392]:
z.dot(y2)

array([[[ 14. ,  32. ],
        [ 32. ,  77. ],
        [ 51.5, 125. ]]])

In [393]:
f = np.random.randint(20, size=(5,3))
f, f.shape

(array([[ 1, 10,  3],
        [11,  6,  5],
        [ 2,  7, 19],
        [ 1, 14, 17],
        [ 0,  1,  0]]),
 (5, 3))

In [394]:
g = np.random.randint(10, size = (2,3))
g, g.shape

(array([[7, 7, 9],
        [2, 3, 2]]),
 (2, 3))

In [395]:
g2 = g.T
g2.shape

(3, 2)

In [396]:
f.dot(g2)

array([[104,  38],
       [164,  50],
       [234,  63],
       [258,  78],
       [  7,   3]])

In [397]:
f2 = f.T

In [398]:
f2, f2.shape

(array([[ 1, 11,  2,  1,  0],
        [10,  6,  7, 14,  1],
        [ 3,  5, 19, 17,  0]]),
 (3, 5))

In [399]:
h = np.random.randint(10, size = (5,2))

In [400]:
product1 = f2.dot(h)

In [401]:
product1, product1.shape

(array([[ 29,  70],
        [115, 197],
        [206, 181]]),
 (3, 2))

# Dot Product Example (product sells)

In [402]:
np.random.seed(seed = 0) 
product_sales = np.random.randint(1, 20, size = (5,3))
product_sales

array([[13, 16,  1],
       [ 4,  4,  8],
       [10, 19,  5],
       [ 7, 13,  2],
       [ 7,  8, 15]])

In [403]:
product_sales_df = pd.DataFrame(product_sales,
                                index = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri'],
                                columns = ['Peanut', 'Cashewnuts', 'Almonds']
                               ) 
product_sales_df

Peanut  Cashewnuts  Almonds
Mon       13          16        1
Tue        4           4        8
Wed       10          19        5
Thur       7          13        2
Fri        7           8       15

In [404]:
product_sales_df.shape

(5, 3)

In [405]:
prices = np.array([10, 8, 12])
type(prices), prices.shape

# The problem I was facing was because I had written the numbers as strings

(numpy.ndarray, (3,))

In [406]:
prices = prices.reshape(1,3)

In [407]:
prices.shape

(1, 3)

In [408]:
prices_df = pd.DataFrame(prices,
                         index = ['Price'],
                         columns = ['Peanut', 'Cashewnuts', 'Almonds']
                        )

In [409]:
prices_df

Peanut  Cashewnuts  Almonds
Price      10           8       12

In [410]:
prices.shape, product_sales.T.shape

((1, 3), (3, 5))

In [411]:
total_sales = prices_df.dot(product_sales_df.T)

In [412]:
total_sales

Mon  Tue  Wed  Thur  Fri
Price  270  168  312   198  314

In [413]:
product_sales_df['Total($)'] = total_sales.T

In [414]:
product_sales_df

Peanut  Cashewnuts  Almonds  Total($)
Mon       13          16        1       270
Tue        4           4        8       168
Wed       10          19        5       312
Thur       7          13        2       198
Fri        7           8       15       314

# Comparison operators

In [415]:
x

array([1, 2, 3])

In [416]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [417]:
x > y

array([[False, False, False],
       [False, False, False]])

In [418]:
y < x

array([[False, False, False],
       [False, False, False]])

In [420]:
y == x

array([[ True,  True,  True],
       [False, False, False]])

In [421]:
y != x

array([[False, False, False],
       [ True,  True,  True]])

# Sorting

In [425]:
np.random.seed(seed = 0)
ages = np.random.randint(99, size = (7, 4))

In [426]:
ages

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [427]:
np.sort(ages)

array([[44, 47, 64, 67],
       [ 9, 21, 67, 83],
       [36, 70, 87, 88],
       [12, 58, 65, 88],
       [39, 46, 87, 88],
       [25, 37, 77, 81],
       [ 9, 20, 72, 80]])

In [429]:
#Sorts the indexes
np.argsort(ages)

array([[0, 1, 2, 3],
       [1, 3, 0, 2],
       [0, 2, 1, 3],
       [1, 2, 3, 0],
       [0, 2, 1, 3],
       [2, 1, 3, 0],
       [1, 2, 0, 3]], dtype=int64)

In [430]:
np.argmin(ages)

5

In [431]:
np.argmax(ages)

11

In [434]:
np.argmax(ages, axis = 0)

array([3, 2, 1, 2], dtype=int64)

In [435]:
np.argmax(ages, axis = 1)

array([3, 2, 3, 0, 3, 0, 3], dtype=int64)

In [436]:
ages

array([[44, 47, 64, 67],
       [67,  9, 83, 21],
       [36, 87, 70, 88],
       [88, 12, 58, 65],
       [39, 87, 46, 88],
       [81, 37, 25, 77],
       [72,  9, 20, 80]])

In [438]:
np.argmin(ages, axis = 0)

array([2, 1, 6, 1], dtype=int64)

# Numpy In Action!!!

<img src='76 - numpy-images/panda.png'/>

In [448]:
from matplotlib.image import imread

In [450]:
panda = imread('76 - numpy-images/panda.png')

In [452]:
panda.dtype

dtype('float32')

In [453]:
type(panda)

numpy.ndarray

In [456]:
panda[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [458]:
panda.ndim

3

In [459]:
panda.size

24465000

3